version: "3.7"

services:
  web:
    container_name: traq3_web
    build:
      context: .
      dockerfile: dev/docker/php8-apache
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - 3000:80
    links:
      - mysql:db

  mysql:
    container_name: traq3_db
    image: mariadb:10
    ports:
      - 3002:3306
    environment:
      - MARIADB_DATABASE=traq
      - MARIADB_USER=traq
      - MARIADB_PASSWORD=dev
      - MARIADB_ROOT_PASSWORD=secret

  phpmyadmin:
    container_name: traq3_pma
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 3003:80
    links:
      - mysql:db
